version: "3.7"

services:
  app:
    image: python:alpine
    command: sh -c "pip install -r Requirements.txt && python -m flask run --host=0.0.0.0 --port=5000"
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    environment: 
      FLASK_APP: app.py
      FLASK_ENV: development